scenarios:
  - "2NGF"
  - "2A"
  # - "2B"
  # - "2C"
  # - "3A"
  # - "3B"
N_rep: 100
rec:
  - '0.1e-8'
  - '0.5e-8'
  - '1e-8'
  - '2e-8'
  - '3e-8'
intervals: [1, 2, 5, 10, 15, 20]
shift_time: [140]
shift_size: [3.0]